services:

  nginx:
    image: nginx:alpine
    restart: always
    command: "/bin/sh -c 'while :; do sleep $RENEW_CHECK & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy:/etc/nginx/conf.d/
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - proxy-network
      - cert-network
  
  certbot:
    image: certbot/certbot:arm64v8-latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep $RENEW_CHECK & wait $${!}; done;'"
    networks:
      - cert-network
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw

  memcached:
    image: memcached
    restart: always
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
  cert-network:
    external: false